import { useState } from "react";
import { Globe, ArrowRight } from "lucide-react";
import { Success } from "../messages/Success";
import { Error } from "../messages/Error";

export default function Verification() {
  const [loading, setLoading] = useState(false);
  const [urls, setUrls] = useState({ success: "", failed: "" });
  const [show, setShow] = useState(false);
  const [saved, isSaved] = useState(false);

  // LOGIC: Check if empty to show the marketing popup
  const handleSaveAttempt = () => {
    if (!urls.success || !urls.failed) {
      setShow(true);
    } else {
      saveData();
    }
  };

  const saveData = async () => {
    setLoading(true);
    try {
      const res = await fetch(
        "https://soteria-client.onrender.com/payment-intent/url-config",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            // Include your auth token here if required by your backend
            Authorization: `Bearer ${localStorage.getItem("token")}`,
          },
          body: JSON.stringify({
            success_url: urls.success,
            failed_url: urls.failed,
          }),
        },
      );

      if (res.ok) {
        isSaved(true);
        Success("Data has been saved");
        // Redirect to dashboard or home after success
        setTimeout(() => isSaved(false), 3000);
      } else {
        Error("Server rejected configuration");
      }
    } catch (e) {
      console.error("failed to setup", e);
      Error("Error while saving data");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="h-170 bg-white flex flex-col items-center justify-center p-6">
      <div className="w-full max-w-md">
        <div className="mb-10">
          <h1 className="text-3xl font-black tracking-tight text-gray-900 mb-2">
            Finish Connection
          </h1>
          <p className="text-gray-500 font-medium">
            Configure where your customers land after checkout.
          </p>
        </div>

        <div className="space-y-6">
          <div className="space-y-2">
            <label className="text-xs font-bold uppercase tracking-widest text-gray-400">
              Success URL
            </label>
            <input
              className="w-full p-4 bg-gray-50 border border-gray-100 rounded-xl focus:ring-2 focus:ring-black outline-none transition-all"
              placeholder="https://your-site.com/success"
              value={urls.success}
              onChange={(e) => setUrls({ ...urls, success: e.target.value })}
            />
          </div>

          <div className="space-y-2">
            <label className="text-xs font-bold uppercase tracking-widest text-gray-400">
              failed URL
            </label>
            <input
              className="w-full p-4 bg-gray-50 border border-gray-100 rounded-xl focus:ring-2 focus:ring-black outline-none transition-all"
              placeholder="https://your-site.com/failed"
              value={urls.failed}
              onChange={(e) => setUrls({ ...urls, failed: e.target.value })}
            />
          </div>

          <button
            onClick={handleSaveAttempt}
            disabled={loading}
            className="cursor-pointer w-full py-4 bg-linear-to-r from-green-500 to-teal-600 text-white rounded-xl font-bold shadow-xl hover:opacity-90 transition-all flex items-center justify-center gap-2"
          >
            {loading ? "Syncing..." : "Complete Setup"}
            <ArrowRight size={18} />
          </button>
        </div>
      </div>

      {show && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center p-6 z-50">
          <div className="bg-white rounded-3xl p-8 max-w-sm w-full shadow-2xl animate-in zoom-in duration-200">
            <div className="w-12 h-12 bg-blue-50 text-green-600 rounded-full flex items-center justify-center mb-6">
              <Globe size={24} />
            </div>
            <h3 className="text-xl font-bold text-gray-900 mb-2">
              No custom URLs?
            </h3>
            <p className="text-gray-500 text-sm leading-relaxed mb-6">
              No problem. We’ll use the <strong>Soteria Pages</strong>. The
              redirect pages will be generated by us.
            </p>
            <div className="space-y-3">
              <button
                onClick={() => {
                  setShow(false);
                  saveData(); // Call the correct function name here
                }}
                className="w-full py-3 bg-emerald-600 text-white rounded-xl border font-bold text-sm cursor-pointer hover:text-emerald-600 hover:border hover:border-green-600 hover:bg-white transition-all"
              >
                Continue with Soteria Pages
              </button>
              <button
                onClick={() => setShow(false)}
                className="w-full py-3 text-gray-400 font-bold text-sm hover:text-gray-600 cursor-pointer"
              >
                Wait, let me add my own
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
